### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'sample_step'

### ISSUE THREAD

**Issue by DeepTitan** [luping-liu/PNDM#1]
Hey! Awesome paper and awesome work. Really impressed.  

So I'm just trying to recreate some of the results with this repo. I am running this:

python main.py --runner sample --method F-PNDM --sample_speed 50 --device cpu --config ddim_cifar10.yml --image_path temp/results --model_path models/ddim_cifar10.ckpt

model is in place, i pip install -r requirements, but for some reason I'm getting this error:

AttributeError: 'Namespace' object has no attribute 'sample_step'

any suggestions?

**Comment by DeepTitan** [comment]
by the way, I am using your model checkpoints from OneDrive in models/ directory

**Comment by liuluping0106** [comment]
First of all, thank you for your appreciation.
Sorry for this bug and I have fixed it now. Hope this can help you.

**Comment by DeepTitan** [comment]
Hey I am back, so i moved the program over to a google colab. Ran this command:


`!python main.py --runner sample --method F-PNDM --sample_speed 50 --device cuda --config ddim_cifar10.yml --image_path results --model_path models/ddim_cifar10.ckpt
`
Everything was going fine and then -> 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/90869054/154008044-f8f02f34-465f-485a-af4f-da63c55c3f7c.png">

any advice?
