### ISSUE TITLE
The  aliyundrive is empty.

### ISSUE THREAD

**Issue by 2862909626** [luping-liu/PNDM#11]
I am writing a paper and need to use your code, but the checkpoint and the fid is empty in the aliyundirve.

**Comment by luping-liu** [comment]
Thanks for the reminder. Aliyundrive sets security reviews and blocks files. I have uploaded a new share link using Google Drive. Enjoy!

**Comment by SYZhang0805** [comment]
Thanks. But I have another question. I used your code in GitHub to train an iDDPM model, but the final FID is 7+, but I used your checkpoint to sample and calculated the FID which is 3.21. Why does this happen? Is there any extra setting that you need to do during training?

**Comment by SYZhang0805** [comment]
Because I am also a student at Zhejiang University, so if you don't mind, can we add a DingTalk friend and communicate on DingTalk

**Comment by luping-liu** [comment]
> Thanks. But I have another question. I used your code in GitHub to train an iDDPM model, but the final FID is 7+, but I used your checkpoint to sample and calculated the FID which is 3.21. Why does this happen? Is there any extra setting that you need to do during training?

PNDM is not designed to optimize the training code. However, you may find my latest project, available at https://github.com/luping-liu/DiffOOD, to be more suitable, as it includes an improved version of the training code.
Btw, perhaps you can send me your wechat ID through email?

**Comment by SYZhang0805** [comment]
I have emailed you, hope to receive your apply! Thank you very much.

**Comment by SYZhang0805** [comment]
I saw that your code includes the training method of iDDPM, DDIM, and PF models, are your checkpoints trained by these codes or obtained from other sources？
