### ISSUE TITLE
Predicted x_0 during denoising

### ISSUE THREAD

**Issue by SnowdenLee** [luping-liu/PNDM#12]
Hi, thanks for the great work! 
I'm wondering is it possible to get a predicted x_0 during the denoising process like DDIM? If yes, could you maybe expalin a bit?
Thanks a lot!

**Comment by CS123n** [comment]
https://github.com/luping-liu/PNDM/blob/e771949c344875ebecda46967de68fc86e970569/runner/method.py#LL148C1-L156C18
I think the simplest way is to use $t$, $e_t$ and $alpha$ to compute $x_0$ and $x_{delta}$ at the same time.
```python
x_0 = th.sqrt(1.0 / at) * x - th.sqrt(1.0 / at - 1) * et
```

**Comment by luping-liu** [comment]
https://github.com/luping-liu/PNDM/blob/e771949c344875ebecda46967de68fc86e970569/runner/method.py#L148-L156

I think the simplest way is to use $t$, $e_t$ and $alpha$ to compute $x_0$ and $x_{delta}$ at the same time.
```python
x_0 = th.sqrt(1.0 / at) * x - th.sqrt(1.0 / at - 1) * et
```
