### ISSUE TITLE
A question of “Pseudo Numerical Method“

### ISSUE THREAD

**Issue by packer-c** [luping-liu/PNDM#13]
Hi, thank you for your interesting work.

I have a question. Is the "pseudo numerical method" one of the methods of classical numerical? Or is it just named specifically for your research? As I searched for the name in the numerical methods domain, but I didn't find it. So I guess it is a specific term you named specifically for your work?

Looking forward to your reply. Thanks!

**Comment by CS123n** [comment]
Our work is inspired by classical numerical methods. However, our motivation is to use a high-order correction for the noise item, which is specific to the diffusion model. The main difference in implementation is the non-linear transfer part, as shown in Table 1 of our paper. Therefore, we call it "pseudo numerical method".

**Comment by luping-liu** [comment]
Our work is inspired by classical numerical methods. However, our motivation is to use a high-order correction for the noise item, which is specific to the diffusion model. The main difference in implementation is the non-linear transfer part, as shown in Table 1 of our paper. Therefore, we call it "pseudo numerical method".

**Comment by packer-c** [comment]
It's clear to me now, Thanks a lot!
