### ISSUE TITLE
Segmentation fault (11)

### ISSUE THREAD

**Issue by DeepTitan** [luping-liu/PNDM#2]
Hey I am back, so i moved the program over to a google colab. Ran this command:

!python main.py --runner sample --method F-PNDM --sample_speed 50 --device cuda --config ddim_cifar10.yml --image_path results --model_path models/ddim_cifar10.ckpt
Everything was going fine and then ->

![image](https://user-images.githubusercontent.com/90869054/154194022-b7c57544-e5c8-4f8f-8696-c6ef6fad97fc.png)

any advice?

**Comment by liuluping0106** [comment]
Maybe your system is running out of memory when trying to execute your code, which results in a segmentation fault.
I think you can change the batch_size smaller in `ddim_cifar10.yml`. Hope this is helpful.

**Comment by luping-liu** [comment]
Maybe your system is running out of memory when trying to execute your code, which results in a segmentation fault.
I think you can change the batch_size smaller in ddim_cifar10.yml. Hope this is helpful.
