### ISSUE TITLE
How do I generate a .ckpt file after training?

### ISSUE THREAD

**Issue by scottp100** [luping-liu/PNDM#3]
After training a model, how do I create a .ckpt file to use with the sample runner? The training loop writes out .pth files that seem _almost_ correct, but they are slightly mismatched. After a bit of research, it appears that the model is saved with the nn.DataParallel module, but is loaded without it. Reference: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/2

**Comment by liuluping0106** [comment]
Sorry for this. 
But you should use the file `ema.pth` and I find it works well for now. I change the name of this file to `ema.ckpt` now. 
Hope this is helpful for you!

**Comment by luping-liu** [comment]
Sorry for this.
But you should use the file `ema.pth` and I find it works well for now. I change the name of this file to `ema.ckpt` now.
Hope this is helpful for you!
