### ISSUE TITLE
Is the implementation for FON really 4-th order?

### ISSUE THREAD

**Issue by qsh-zh** [luping-liu/PNDM#5]
Thanks for your inspiring work.

I found the implementation of [FON](https://github.com/luping-liu/PNDM/blob/180da56ae1a4338c0c468219cbc27292043e0538/runner/method.py#L55) is confusing, which may not what claimed in the paper.

Paper claims
![image](https://user-images.githubusercontent.com/28699575/161296735-f0a01717-ce18-4aba-8d20-87ba2be387bd.png)

However, 
```
def gen_fon(img, t, t_next, model, alphas_cump, ets):
    t_list = [t, (t + t_next) / 2.0, t_next]
    if len(ets) > 2:
        noise = model(img, t)
        img_next = transfer(img, t, t-1, noise, alphas_cump)
        delta = img_next - img
        ets.append(delta)
    else:
        noise = model(img, t_list[0])
        img_ = transfer(img, t, t - 1, noise, alphas_cump)
        delta_1 = img_ - img
        ets.append(delta_1)

        img_2 = img + delta_1 * (t - t_next).view(-1, 1, 1, 1) / 2.0
        noise = model(img_2, t_list[1])
        img_ = transfer(img, t, t - 1, noise, alphas_cump)
        delta_2 = img_ - img

        img_3 = img + delta_2 * (t - t_next).view(-1, 1, 1, 1) / 2.0
        noise = model(img_3, t_list[1])
        img_ = transfer(img, t, t - 1, noise, alphas_cump)
        delta_3 = img_ - img

        img_4 = img + delta_3 * (t - t_next).view(-1, 1, 1, 1)
        noise = model(img_4, t_list[2])
        img_ = transfer(img, t, t - 1, noise, alphas_cump)
        delta_4 = img_ - img
        delta = (1 / 6.0) * (delta_1 + 2*delta_2 + 2*delta_3 + delta_4)

    img_next = img + delta * (t - t_next).view(-1, 1, 1, 1)
    return img_next
```

After `len(ets) > 2`, delta seems only use first order info?

**Comment by luping-liu** [comment]
Yes, you are right. I have fixed this bug. Replace this first-order method with the linear multistep method.
This public code is a reconstruction of our experimental code, so this bug does not influence our results.

**Comment by qsh-zh** [comment]
Thanks for your quick response!!!

**Comment by qsh-zh** [comment]
I want to point out another related issue, still for this function
```
    img_next = img + delta * (t - t_next).view(-1, 1, 1, 1)
```

But actually, the used delta is already relative change (img_next - img) instead of gradient or speed. Does it need to multi delta t again considering you are using unifomal delta_t?

**Comment by luping-liu** [comment]
Well, please notice the difference between
https://github.com/luping-liu/PNDM/blob/f285e8e6da36049ea29e97b741fb71e531505ec8/runner/method.py#L57-L58
and
https://github.com/luping-liu/PNDM/blob/f285e8e6da36049ea29e97b741fb71e531505ec8/runner/method.py#L96
In fact, we use the delta from t to t-1 to approximate the gradient in FON.

**Comment by qsh-zh** [comment]
I see, thanks for your response!!!
