### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by zzw-zwzhang** [luping-liu/PNDM#6]
Hi, thanks for your interesting work.

What is your training time on each dataset?

**Comment by CS123n** [comment]
In our paper, we use pre-trained models from other papers. 
We also train new models by ourselves and find maybe 24h is enough for cifar10 using 2 GPUs and set batch_size 256.

**Comment by luping-liu** [comment]
In our paper, we use pre-trained models from other papers.
We also train new models by ourselves and find maybe 24h is enough for cifar10 using 2 GPUs and set batch_size 256.

**Comment by zzw-zwzhang** [comment]
> In our paper, we use pre-trained models from other papers.
> We also train new models by ourselves and find maybe 24h is enough for cifar10 using 2 RTX3090s and set batch_size 25

**Comment by zzw-zwzhang** [comment]
Thank you for your reply.

I use the default DDIM code to train the cifar with 80w steps, but fid is 187. I will try your code again.

**Comment by zzw-zwzhang** [comment]
Hi, I retrained the CIFAR10 based on your default parameters, but the reproduced result is worse than your provided model. For example,
DDIM 50 steps: 6.1640 vs. 14.3992

`Python main.py --runner train --device cuda --config ddim_cifar10.yml --method DDIM --train_path temp/train`

Can you provide any suggestions?

**Comment by zzw-zwzhang** [comment]
Thanks for your reply. I will try it again.

Before that, I had trained the model based on the DDIM code, but it failed.
[https://github.com/ermongroup/ddim/issues/6#issue-1230873595](https://github.com/ermongroup/ddim/issues/6#issue-1230873595)\

**Comment by luping-liu** [comment]
Perhaps you can refer to my other code [DiffOOD](https://github.com/luping-liu/DiffOOD), which contains the complete training code. I get FID 3.2 on CIFAR10 by myself.
