### ISSUE TITLE
Conditional PNDM

### ISSUE THREAD

**Issue by ELlight07** [luping-liu/PNDM#8]
Hi, I wanted to use PNDM for conditional image generation and would like to know how to integrate that. Thanks

**Comment by luping-liu** [comment]
Perhaps you can refer to my other code [DiffOOD](https://github.com/luping-liu/DiffOOD), which contains class-condition diffusion models.
I also recommend that you use [stable diffusion](https://github.com/CompVis/stable-diffusion), which supports more different types of conditions.
